# Anna KaRNNa

In this notebook, I'll build a character-wise RNN trained on Anna Karenina, one of my all-time favorite books. It'll be able to generate new text based on the text from the book.

This network is based off of Andrej Karpathy's [post on RNNs](http://karpathy.github.io/2015/05/21/rnn-effectiveness/) and [implementation in Torch](https://github.com/karpathy/char-rnn). Also, some information [here at r2rt](http://r2rt.com/recurrent-neural-networks-in-tensorflow-ii.html) and from [Sherjil Ozair](https://github.com/sherjilozair/char-rnn-tensorflow) on GitHub. Below is the general architecture of the character-wise RNN.

<img src="assets/charseq.jpeg" width="500">

In [2]:
import time
from collections import namedtuple

import numpy as np
import tensorflow as tf

First we'll load the text file and convert it into integers for our network to use. Here I'm creating a couple dictionaries to convert the characters to and from integers. Encoding the characters as integers makes it easier to use as input in the network.

In [3]:
with open('anna.txt', 'r') as f:
    text=f.read()
vocab = set(text)
vocab_to_int = {c: i for i, c in enumerate(vocab)}
int_to_vocab = dict(enumerate(vocab))
encoded = np.array([vocab_to_int[c] for c in text], dtype=np.int32)

Let's check out the first 100 characters, make sure everything is peachy. According to the [American Book Review](http://americanbookreview.org/100bestlines.asp), this is the 6th best first line of a book ever.

In [4]:
text[:100]

'Chapter 1\n\n\nHappy families are all alike; every unhappy family is unhappy in its own\nway.\n\nEverythin'

And we can see the characters encoded as integers.

In [5]:
encoded[:100]

array([55, 63, 69, 22,  6, 76, 45,  5, 16, 35, 35, 35,  2, 69, 22, 22, 33,
        5, 58, 69,  1, 29, 43, 29, 76, 78,  5, 69, 45, 76,  5, 69, 43, 43,
        5, 69, 43, 29, 17, 76, 34,  5, 76, 48, 76, 45, 33,  5, 39, 12, 63,
       69, 22, 22, 33,  5, 58, 69,  1, 29, 43, 33,  5, 29, 78,  5, 39, 12,
       63, 69, 22, 22, 33,  5, 29, 12,  5, 29,  6, 78,  5, 52, 36, 12, 35,
       36, 69, 33, 61, 35, 35, 44, 48, 76, 45, 33,  6, 63, 29, 12], dtype=int32)

Since the network is working with individual characters, it's similar to a classification problem in which we are trying to predict the next character from the previous text.  Here's how many 'classes' our network has to pick from.

In [6]:
len(vocab)

83

## Making training mini-batches

Here is where we'll make our mini-batches for training. Remember that we want our batches to be multiple sequences of some desired number of sequence steps. Considering a simple example, our batches would look like this:

<img src="assets/sequence_batching@1x.png" width=500px>


<br>
We have our text encoded as integers as one long array in `encoded`. Let's create a function that will give us an iterator for our batches. I like using [generator functions](https://jeffknupp.com/blog/2013/04/07/improve-your-python-yield-and-generators-explained/) to do this. Then we can pass `encoded` into this function and get our batch generator.

The first thing we need to do is discard some of the text so we only have completely full batches. Each batch contains $N \times M$ characters, where $N$ is the batch size (the number of sequences) and $M$ is the number of steps. Then, to get the number of batches we can make from some array `arr`, you divide the length of `arr` by the batch size. Once you know the number of batches and the batch size, you can get the total number of characters to keep.

After that, we need to split `arr` into $N$ sequences. You can do this using `arr.reshape(size)` where `size` is a tuple containing the dimensions sizes of the reshaped array. We know we want $N$ sequences (`n_seqs` below), let's make that the size of the first dimension. For the second dimension, you can use `-1` as a placeholder in the size, it'll fill up the array with the appropriate data for you. After this, you should have an array that is $N \times (M * K)$ where $K$ is the number of batches.

Now that we have this array, we can iterate through it to get our batches. The idea is each batch is a $N \times M$ window on the array. For each subsequent batch, the window moves over by `n_steps`. We also want to create both the input and target arrays. Remember that the targets are the inputs shifted over one character. You'll usually see the first input character used as the last target character, so something like this:
```python
y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
```
where `x` is the input batch and `y` is the target batch.

The way I like to do this window is use `range` to take steps of size `n_steps` from $0$ to `arr.shape[1]`, the total number of steps in each sequence. That way, the integers you get from `range` always point to the start of a batch, and each window is `n_steps` wide.

In [7]:
def get_batches(arr, n_seqs, n_steps):
    '''Create a generator that returns batches of size
       n_seqs x n_steps from arr.
       
       Arguments
       ---------
       arr: Array you want to make batches from
       n_seqs: Batch size, the number of sequences per batch
       n_steps: Number of sequence steps per batch
    '''
    # Get the batch size and number of batches we can make
    batch_size = n_seqs * n_steps
    n_batches = len(arr)//batch_size
    
    # Keep only enough characters to make full batches
    arr = arr[:n_batches * batch_size]
    
    # Reshape into n_seqs rows
    arr = arr.reshape((n_seqs, -1))
    
    for n in range(0, arr.shape[1], n_steps):
        # The features
        x = arr[:, n:n+n_steps]
        # The targets, shifted by one
        y = np.zeros_like(x)
        y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
        yield x, y

Now I'll make my data sets and we can check out what's going on here. Here I'm going to use a batch size of 10 and 50 sequence steps.

In [8]:
batches = get_batches(encoded, 10, 50)
x, y = next(batches)

In [9]:
print('x\n', x[:10, :10])
print('\ny\n', y[:10, :10])

x
 [[55 63 69 22  6 76 45  5 16 35]
 [ 5 69  1  5 12 52  6  5 56 52]
 [48 29 12 61 35 35  8 64 76 78]
 [12  5 24 39 45 29 12 56  5 63]
 [ 5 29  6  5 29 78 28  5 78 29]
 [ 5 13  6  5 36 69 78 35 52 12]
 [63 76 12  5 18 52  1 76  5 58]
 [34  5 73 39  6  5 12 52 36  5]
 [ 6  5 29 78 12 79  6 61  5 59]
 [ 5 78 69 29 24  5  6 52  5 63]]

y
 [[63 69 22  6 76 45  5 16 35 35]
 [69  1  5 12 52  6  5 56 52 29]
 [29 12 61 35 35  8 64 76 78 28]
 [ 5 24 39 45 29 12 56  5 63 29]
 [29  6  5 29 78 28  5 78 29 45]
 [13  6  5 36 69 78 35 52 12 43]
 [76 12  5 18 52  1 76  5 58 52]
 [ 5 73 39  6  5 12 52 36  5 78]
 [ 5 29 78 12 79  6 61  5 59 63]
 [78 69 29 24  5  6 52  5 63 76]]


If you implemented `get_batches` correctly, the above output should look something like 
```
x
 [[55 63 69 22  6 76 45  5 16 35]
 [ 5 69  1  5 12 52  6  5 56 52]
 [48 29 12 61 35 35  8 64 76 78]
 [12  5 24 39 45 29 12 56  5 63]
 [ 5 29  6  5 29 78 28  5 78 29]
 [ 5 13  6  5 36 69 78 35 52 12]
 [63 76 12  5 18 52  1 76  5 58]
 [34  5 73 39  6  5 12 52 36  5]
 [ 6  5 29 78 12 79  6 61  5 59]
 [ 5 78 69 29 24  5  6 52  5 63]]

y
 [[63 69 22  6 76 45  5 16 35 35]
 [69  1  5 12 52  6  5 56 52 29]
 [29 12 61 35 35  8 64 76 78 28]
 [ 5 24 39 45 29 12 56  5 63 29]
 [29  6  5 29 78 28  5 78 29 45]
 [13  6  5 36 69 78 35 52 12 43]
 [76 12  5 18 52  1 76  5 58 52]
 [ 5 73 39  6  5 12 52 36  5 78]
 [ 5 29 78 12 79  6 61  5 59 63]
 [78 69 29 24  5  6 52  5 63 76]]
 ```
 although the exact numbers will be different. Check to make sure the data is shifted over one step for `y`.

## Building the model

Below is where you'll build the network. We'll break it up into parts so it's easier to reason about each bit. Then we can connect them up into the whole network.

<img src="assets/charRNN.png" width=500px>


### Inputs

First off we'll create our input placeholders. As usual we need placeholders for the training data and the targets. We'll also create a placeholder for dropout layers called `keep_prob`.

In [10]:
def build_inputs(batch_size, num_steps):
    ''' Define placeholders for inputs, targets, and dropout 
    
        Arguments
        ---------
        batch_size: Batch size, number of sequences per batch
        num_steps: Number of sequence steps in a batch
        
    '''
    # Declare placeholders we'll feed into the graph
    inputs = tf.placeholder(tf.int32, [batch_size, num_steps], name='inputs')
    targets = tf.placeholder(tf.int32, [batch_size, num_steps], name='targets')
    
    # Keep probability placeholder for drop out layers
    keep_prob = tf.placeholder(tf.float32, name='keep_prob')
    
    return inputs, targets, keep_prob

### LSTM Cell

Here we will create the LSTM cell we'll use in the hidden layer. We'll use this cell as a building block for the RNN. So we aren't actually defining the RNN here, just the type of cell we'll use in the hidden layer.

We first create a basic LSTM cell with

```python
lstm = tf.contrib.rnn.BasicLSTMCell(num_units)
```

where `num_units` is the number of units in the hidden layers in the cell. Then we can add dropout by wrapping it with 

```python
tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
```
You pass in a cell and it will automatically add dropout to the inputs or outputs. Finally, we can stack up the LSTM cells into layers with [`tf.contrib.rnn.MultiRNNCell`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/contrib/rnn/MultiRNNCell). With this, you pass in a list of cells and it will send the output of one cell into the next cell. For example,

```python
tf.contrib.rnn.MultiRNNCell([cell]*num_layers)
```

This might look a little weird if you know Python well because this will create a list of the same `cell` object. However, TensorFlow will create different weight matrices for all `cell` objects. Even though this is actually multiple LSTM cells stacked on each other, you can treat the multiple layers as one cell.

We also need to create an initial cell state of all zeros. This can be done like so

```python
initial_state = cell.zero_state(batch_size, tf.float32)
```

Below, we implement the `build_lstm` function to create these LSTM cells and the initial state.

In [11]:
def build_lstm(lstm_size, num_layers, batch_size, keep_prob):
    ''' Build LSTM cell.
    
        Arguments
        ---------
        keep_prob: Scalar tensor (tf.placeholder) for the dropout keep probability
        lstm_size: Size of the hidden layers in the LSTM cells
        num_layers: Number of LSTM layers
        batch_size: Batch size

    '''
    ### Build the LSTM Cell
    # Use a basic LSTM cell
    lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size)
    
    # Add dropout to the cell
    drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
    
    # Stack up multiple LSTM layers, for deep learning
    cell = tf.contrib.rnn.MultiRNNCell([drop] * num_layers)
    initial_state = cell.zero_state(batch_size, tf.float32)
    
    return cell, initial_state

### RNN Output

Here we'll create the output layer. We need to connect the output of the RNN cells to a full connected layer with a softmax output. The softmax output gives us a probability distribution we can use to predict the next character.

If our input has batch size $N$, number of steps $M$, and the hidden layer has $L$ hidden units, then the output is a 3D tensor with size $N \times M \times L$. The output of each LSTM cell has size $L$, we have $M$ of them, one for each sequence step, and we have $N$ sequences. So the total size is $N \times M \times L$.

We are using the same fully connected layer, the same weights, for each of the outputs. Then, to make things easier, we should reshape the outputs into a 2D tensor with shape $(M * N) \times L$. That is, one row for each sequence and step, where the values of each row are the output from the LSTM cells.

One we have the outputs reshaped, we can do the matrix multiplication with the weights. We need to wrap the weight and bias variables in a variable scope with `tf.variable_scope(scope_name)` because there are weights being created in the LSTM cells. TensorFlow will throw an error if the weights created here have the same names as the weights created in the LSTM cells, which they will be default. To avoid this, we wrap the variables in a variable scope so we can give them unique names.

In [12]:
def build_output(lstm_output, in_size, out_size):
    ''' Build a softmax layer, return the softmax output and logits.
    
        Arguments
        ---------
        
        x: Input tensor
        in_size: Size of the input tensor, for example, size of the LSTM cells
        out_size: Size of this softmax layer
    
    '''

    # Reshape output so it's a bunch of rows, one row for each step for each sequence.
    # That is, the shape should be batch_size*num_steps rows by lstm_size columns
    seq_output = tf.concat(lstm_output, axis=1)
    x = tf.reshape(seq_output, [-1, in_size])
    
    # Connect the RNN outputs to a softmax layer
    with tf.variable_scope('softmax'):
        softmax_w = tf.Variable(tf.truncated_normal((in_size, out_size), stddev=0.1))
        softmax_b = tf.Variable(tf.zeros(out_size))
    
    # Since output is a bunch of rows of RNN cell outputs, logits will be a bunch
    # of rows of logit outputs, one for each step and sequence
    logits = tf.matmul(x, softmax_w) + softmax_b
    
    # Use softmax to get the probabilities for predicted characters
    out = tf.nn.softmax(logits, name='predictions')
    
    return out, logits

### Training loss

Next up is the training loss. We get the logits and targets and calculate the softmax cross-entropy loss. First we need to one-hot encode the targets, we're getting them as encoded characters. Then, reshape the one-hot targets so it's a 2D tensor with size $(M*N) \times C$ where $C$ is the number of classes/characters we have. Remember that we reshaped the LSTM outputs and ran them through a fully connected layer with $C$ units. So our logits will also have size $(M*N) \times C$.

Then we run the logits and targets through `tf.nn.softmax_cross_entropy_with_logits` and find the mean to get the loss.

In [13]:
def build_loss(logits, targets, lstm_size, num_classes):
    ''' Calculate the loss from the logits and the targets.
    
        Arguments
        ---------
        logits: Logits from final fully connected layer
        targets: Targets for supervised learning
        lstm_size: Number of LSTM hidden units
        num_classes: Number of classes in targets
        
    '''
    
    # One-hot encode targets and reshape to match logits, one row per batch_size per step
    y_one_hot = tf.one_hot(targets, num_classes)
    y_reshaped = tf.reshape(y_one_hot, logits.get_shape())
    
    # Softmax cross entropy loss
    loss = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y_reshaped)
    loss = tf.reduce_mean(loss)
    return loss

### Optimizer

Here we build the optimizer. Normal RNNs have have issues gradients exploding and disappearing. LSTMs fix the disappearance problem, but the gradients can still grow without bound. To fix this, we can clip the gradients above some threshold. That is, if a gradient is larger than that threshold, we set it to the threshold. This will ensure the gradients never grow overly large. Then we use an AdamOptimizer for the learning step.

In [14]:
def build_optimizer(loss, learning_rate, grad_clip):
    ''' Build optmizer for training, using gradient clipping.
    
        Arguments:
        loss: Network loss
        learning_rate: Learning rate for optimizer
    
    '''
    
    # Optimizer for training, using gradient clipping to control exploding gradients
    tvars = tf.trainable_variables()
    grads, _ = tf.clip_by_global_norm(tf.gradients(loss, tvars), grad_clip)
    train_op = tf.train.AdamOptimizer(learning_rate)
    optimizer = train_op.apply_gradients(zip(grads, tvars))
    
    return optimizer

### Build the network

Now we can put all the pieces together and build a class for the network. To actually run data through the LSTM cells, we will use [`tf.nn.dynamic_rnn`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/nn/dynamic_rnn). This function will pass the hidden and cell states across LSTM cells appropriately for us. It returns the outputs for each LSTM cell at each step for each sequence in the mini-batch. It also gives us the final LSTM state. We want to save this state as `final_state` so we can pass it to the first LSTM cell in the the next mini-batch run. For `tf.nn.dynamic_rnn`, we pass in the cell and initial state we get from `build_lstm`, as well as our input sequences. Also, we need to one-hot encode the inputs before going into the RNN. 

In [15]:
class CharRNN:
    
    def __init__(self, num_classes, batch_size=64, num_steps=50, 
                       lstm_size=128, num_layers=2, learning_rate=0.001, 
                       grad_clip=5, sampling=False):
    
        # When we're using this network for sampling later, we'll be passing in
        # one character at a time, so providing an option for that
        if sampling == True:
            batch_size, num_steps = 1, 1
        else:
            batch_size, num_steps = batch_size, num_steps

        tf.reset_default_graph()
        
        # Build the input placeholder tensors
        self.inputs, self.targets, self.keep_prob = build_inputs(batch_size, num_steps)

        # Build the LSTM cell
        cell, self.initial_state = build_lstm(lstm_size, num_layers, batch_size, self.keep_prob)

        ### Run the data through the RNN layers
        # First, one-hot encode the input tokens
        x_one_hot = tf.one_hot(self.inputs, num_classes)
        
        # Run each sequence step through the RNN and collect the outputs
        outputs, state = tf.nn.dynamic_rnn(cell, x_one_hot, initial_state=self.initial_state)
        self.final_state = state
        
        # Get softmax predictions and logits
        self.prediction, self.logits = build_output(outputs, lstm_size, num_classes)
        
        # Loss and optimizer (with gradient clipping)
        self.loss = build_loss(self.logits, self.targets, lstm_size, num_classes)
        self.optimizer = build_optimizer(self.loss, learning_rate, grad_clip)

## Hyperparameters

Here I'm defining the hyperparameters for the network. 

* `batch_size` - Number of sequences running through the network in one pass.
* `num_steps` - Number of characters in the sequence the network is trained on. Larger is better typically, the network will learn more long range dependencies. But it takes longer to train. 100 is typically a good number here.
* `lstm_size` - The number of units in the hidden layers.
* `num_layers` - Number of hidden LSTM layers to use
* `learning_rate` - Learning rate for training
* `keep_prob` - The dropout keep probability when training. If you're network is overfitting, try decreasing this.

Here's some good advice from Andrej Karpathy on training the network. I'm going to copy it in here for your benefit, but also link to [where it originally came from](https://github.com/karpathy/char-rnn#tips-and-tricks).

> ## Tips and Tricks

>### Monitoring Validation Loss vs. Training Loss
>If you're somewhat new to Machine Learning or Neural Networks it can take a bit of expertise to get good models. The most important quantity to keep track of is the difference between your training loss (printed during training) and the validation loss (printed once in a while when the RNN is run on the validation data (by default every 1000 iterations)). In particular:

> - If your training loss is much lower than validation loss then this means the network might be **overfitting**. Solutions to this are to decrease your network size, or to increase dropout. For example you could try dropout of 0.5 and so on.
> - If your training/validation loss are about equal then your model is **underfitting**. Increase the size of your model (either number of layers or the raw number of neurons per layer)

> ### Approximate number of parameters

> The two most important parameters that control the model are `lstm_size` and `num_layers`. I would advise that you always use `num_layers` of either 2/3. The `lstm_size` can be adjusted based on how much data you have. The two important quantities to keep track of here are:

> - The number of parameters in your model. This is printed when you start training.
> - The size of your dataset. 1MB file is approximately 1 million characters.

>These two should be about the same order of magnitude. It's a little tricky to tell. Here are some examples:

> - I have a 100MB dataset and I'm using the default parameter settings (which currently print 150K parameters). My data size is significantly larger (100 mil >> 0.15 mil), so I expect to heavily underfit. I am thinking I can comfortably afford to make `lstm_size` larger.
> - I have a 10MB dataset and running a 10 million parameter model. I'm slightly nervous and I'm carefully monitoring my validation loss. If it's larger than my training loss then I may want to try to increase dropout a bit and see if that helps the validation loss.

> ### Best models strategy

>The winning strategy to obtaining very good models (if you have the compute time) is to always err on making the network larger (as large as you're willing to wait for it to compute) and then try different dropout values (between 0,1). Whatever model has the best validation performance (the loss, written in the checkpoint filename, low is good) is the one you should use in the end.

>It is very common in deep learning to run many different models with many different hyperparameter settings, and in the end take whatever checkpoint gave the best validation performance.

>By the way, the size of your training and validation splits are also parameters. Make sure you have a decent amount of data in your validation set or otherwise the validation performance will be noisy and not very informative.


In [16]:
batch_size = 100        # Sequences per batch
num_steps = 100         # Number of sequence steps per batch
lstm_size = 512         # Size of hidden layers in LSTMs
num_layers = 2          # Number of LSTM layers
learning_rate = 0.001   # Learning rate
keep_prob = 0.5         # Dropout keep probability

## Time for training

This is typical training code, passing inputs and targets into the network, then running the optimizer. Here we also get back the final LSTM state for the mini-batch. Then, we pass that state back into the network so the next batch can continue the state from the previous batch. And every so often (set by `save_every_n`) I save a checkpoint.

Here I'm saving checkpoints with the format

`i{iteration number}_l{# hidden layer units}.ckpt`

In [21]:
epochs = 20
# Save every N iterations
save_every_n = 200

model = CharRNN(len(vocab), batch_size=batch_size, num_steps=num_steps,
                lstm_size=lstm_size, num_layers=num_layers, 
                learning_rate=learning_rate)

saver = tf.train.Saver(max_to_keep=100)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    # Use the line below to load a checkpoint and resume training
    #saver.restore(sess, 'checkpoints/______.ckpt')
    counter = 0
    for e in range(epochs):
        # Train network
        new_state = sess.run(model.initial_state)
        loss = 0
        for x, y in get_batches(encoded, batch_size, num_steps):
            counter += 1
            start = time.time()
            feed = {model.inputs: x,
                    model.targets: y,
                    model.keep_prob: keep_prob,
                    model.initial_state: new_state}
            batch_loss, new_state, _ = sess.run([model.loss, 
                                                 model.final_state, 
                                                 model.optimizer], 
                                                 feed_dict=feed)
            
            end = time.time()
            print('Epoch: {}/{}... '.format(e+1, epochs),
                  'Training Step: {}... '.format(counter),
                  'Training loss: {:.4f}... '.format(batch_loss),
                  '{:.4f} sec/batch'.format((end-start)))
        
            if (counter % save_every_n == 0):
                saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))
    
    saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))

Epoch: 1/20...  Training Step: 1...  Training loss: 4.4178...  0.1997 sec/batch
Epoch: 1/20...  Training Step: 2...  Training loss: 4.3329...  0.1566 sec/batch
Epoch: 1/20...  Training Step: 3...  Training loss: 3.8995...  0.1491 sec/batch
Epoch: 1/20...  Training Step: 4...  Training loss: 5.5604...  0.1464 sec/batch
Epoch: 1/20...  Training Step: 5...  Training loss: 3.9864...  0.1480 sec/batch
Epoch: 1/20...  Training Step: 6...  Training loss: 3.9316...  0.1463 sec/batch
Epoch: 1/20...  Training Step: 7...  Training loss: 3.7652...  0.1483 sec/batch
Epoch: 1/20...  Training Step: 8...  Training loss: 3.6055...  0.1458 sec/batch
Epoch: 1/20...  Training Step: 9...  Training loss: 3.4638...  0.1465 sec/batch
Epoch: 1/20...  Training Step: 10...  Training loss: 3.4104...  0.1450 sec/batch
Epoch: 1/20...  Training Step: 11...  Training loss: 3.3789...  0.1467 sec/batch
Epoch: 1/20...  Training Step: 12...  Training loss: 3.4101...  0.1467 sec/batch
Epoch: 1/20...  Training Step: 13... 

Epoch: 1/20...  Training Step: 103...  Training loss: 3.0910...  0.1486 sec/batch
Epoch: 1/20...  Training Step: 104...  Training loss: 3.0869...  0.1477 sec/batch
Epoch: 1/20...  Training Step: 105...  Training loss: 3.0824...  0.1465 sec/batch
Epoch: 1/20...  Training Step: 106...  Training loss: 3.0828...  0.1466 sec/batch
Epoch: 1/20...  Training Step: 107...  Training loss: 3.0561...  0.1490 sec/batch
Epoch: 1/20...  Training Step: 108...  Training loss: 3.0640...  0.1476 sec/batch
Epoch: 1/20...  Training Step: 109...  Training loss: 3.0704...  0.1470 sec/batch
Epoch: 1/20...  Training Step: 110...  Training loss: 3.0348...  0.1475 sec/batch
Epoch: 1/20...  Training Step: 111...  Training loss: 3.0521...  0.1462 sec/batch
Epoch: 1/20...  Training Step: 112...  Training loss: 3.0492...  0.1480 sec/batch
Epoch: 1/20...  Training Step: 113...  Training loss: 3.1013...  0.1489 sec/batch
Epoch: 1/20...  Training Step: 114...  Training loss: 3.0985...  0.1464 sec/batch
Epoch: 1/20...  

Epoch: 2/20...  Training Step: 203...  Training loss: 2.4915...  0.1497 sec/batch
Epoch: 2/20...  Training Step: 204...  Training loss: 2.4868...  0.1496 sec/batch
Epoch: 2/20...  Training Step: 205...  Training loss: 2.4942...  0.1475 sec/batch
Epoch: 2/20...  Training Step: 206...  Training loss: 2.4897...  0.1468 sec/batch
Epoch: 2/20...  Training Step: 207...  Training loss: 2.4990...  0.1477 sec/batch
Epoch: 2/20...  Training Step: 208...  Training loss: 2.4754...  0.1474 sec/batch
Epoch: 2/20...  Training Step: 209...  Training loss: 2.4678...  0.1469 sec/batch
Epoch: 2/20...  Training Step: 210...  Training loss: 2.4808...  0.1469 sec/batch
Epoch: 2/20...  Training Step: 211...  Training loss: 2.4629...  0.1459 sec/batch
Epoch: 2/20...  Training Step: 212...  Training loss: 2.5062...  0.1466 sec/batch
Epoch: 2/20...  Training Step: 213...  Training loss: 2.4719...  0.1468 sec/batch
Epoch: 2/20...  Training Step: 214...  Training loss: 2.4695...  0.1464 sec/batch
Epoch: 2/20...  

Epoch: 2/20...  Training Step: 303...  Training loss: 2.2445...  0.1464 sec/batch
Epoch: 2/20...  Training Step: 304...  Training loss: 2.2462...  0.1463 sec/batch
Epoch: 2/20...  Training Step: 305...  Training loss: 2.2492...  0.1472 sec/batch
Epoch: 2/20...  Training Step: 306...  Training loss: 2.2775...  0.1488 sec/batch
Epoch: 2/20...  Training Step: 307...  Training loss: 2.2664...  0.1466 sec/batch
Epoch: 2/20...  Training Step: 308...  Training loss: 2.2324...  0.1478 sec/batch
Epoch: 2/20...  Training Step: 309...  Training loss: 2.2441...  0.1465 sec/batch
Epoch: 2/20...  Training Step: 310...  Training loss: 2.2561...  0.1479 sec/batch
Epoch: 2/20...  Training Step: 311...  Training loss: 2.2341...  0.1465 sec/batch
Epoch: 2/20...  Training Step: 312...  Training loss: 2.2189...  0.1474 sec/batch
Epoch: 2/20...  Training Step: 313...  Training loss: 2.2179...  0.1482 sec/batch
Epoch: 2/20...  Training Step: 314...  Training loss: 2.1948...  0.1474 sec/batch
Epoch: 2/20...  

Epoch: 3/20...  Training Step: 403...  Training loss: 2.0991...  0.1505 sec/batch
Epoch: 3/20...  Training Step: 404...  Training loss: 2.0952...  0.1485 sec/batch
Epoch: 3/20...  Training Step: 405...  Training loss: 2.1287...  0.1484 sec/batch
Epoch: 3/20...  Training Step: 406...  Training loss: 2.0938...  0.1485 sec/batch
Epoch: 3/20...  Training Step: 407...  Training loss: 2.0799...  0.1481 sec/batch
Epoch: 3/20...  Training Step: 408...  Training loss: 2.0800...  0.1479 sec/batch
Epoch: 3/20...  Training Step: 409...  Training loss: 2.1055...  0.1482 sec/batch
Epoch: 3/20...  Training Step: 410...  Training loss: 2.1335...  0.1474 sec/batch
Epoch: 3/20...  Training Step: 411...  Training loss: 2.0908...  0.1471 sec/batch
Epoch: 3/20...  Training Step: 412...  Training loss: 2.0808...  0.1481 sec/batch
Epoch: 3/20...  Training Step: 413...  Training loss: 2.0789...  0.1489 sec/batch
Epoch: 3/20...  Training Step: 414...  Training loss: 2.1235...  0.1477 sec/batch
Epoch: 3/20...  

Epoch: 3/20...  Training Step: 503...  Training loss: 1.9737...  0.1474 sec/batch
Epoch: 3/20...  Training Step: 504...  Training loss: 1.9906...  0.1482 sec/batch
Epoch: 3/20...  Training Step: 505...  Training loss: 1.9865...  0.1474 sec/batch
Epoch: 3/20...  Training Step: 506...  Training loss: 1.9788...  0.1471 sec/batch
Epoch: 3/20...  Training Step: 507...  Training loss: 1.9649...  0.1483 sec/batch
Epoch: 3/20...  Training Step: 508...  Training loss: 1.9651...  0.1478 sec/batch
Epoch: 3/20...  Training Step: 509...  Training loss: 1.9668...  0.1471 sec/batch
Epoch: 3/20...  Training Step: 510...  Training loss: 1.9612...  0.1480 sec/batch
Epoch: 3/20...  Training Step: 511...  Training loss: 1.9527...  0.1486 sec/batch
Epoch: 3/20...  Training Step: 512...  Training loss: 1.9262...  0.1477 sec/batch
Epoch: 3/20...  Training Step: 513...  Training loss: 1.9580...  0.1470 sec/batch
Epoch: 3/20...  Training Step: 514...  Training loss: 1.9567...  0.1488 sec/batch
Epoch: 3/20...  

Epoch: 4/20...  Training Step: 603...  Training loss: 1.9265...  0.1501 sec/batch
Epoch: 4/20...  Training Step: 604...  Training loss: 1.8877...  0.1480 sec/batch
Epoch: 4/20...  Training Step: 605...  Training loss: 1.8672...  0.1470 sec/batch
Epoch: 4/20...  Training Step: 606...  Training loss: 1.8664...  0.1465 sec/batch
Epoch: 4/20...  Training Step: 607...  Training loss: 1.8811...  0.1481 sec/batch
Epoch: 4/20...  Training Step: 608...  Training loss: 1.9223...  0.1469 sec/batch
Epoch: 4/20...  Training Step: 609...  Training loss: 1.8733...  0.1477 sec/batch
Epoch: 4/20...  Training Step: 610...  Training loss: 1.8713...  0.1484 sec/batch
Epoch: 4/20...  Training Step: 611...  Training loss: 1.8748...  0.1491 sec/batch
Epoch: 4/20...  Training Step: 612...  Training loss: 1.9166...  0.1469 sec/batch
Epoch: 4/20...  Training Step: 613...  Training loss: 1.8814...  0.1475 sec/batch
Epoch: 4/20...  Training Step: 614...  Training loss: 1.8868...  0.1486 sec/batch
Epoch: 4/20...  

Epoch: 4/20...  Training Step: 703...  Training loss: 1.8109...  0.1485 sec/batch
Epoch: 4/20...  Training Step: 704...  Training loss: 1.8253...  0.1480 sec/batch
Epoch: 4/20...  Training Step: 705...  Training loss: 1.8110...  0.1471 sec/batch
Epoch: 4/20...  Training Step: 706...  Training loss: 1.7860...  0.1475 sec/batch
Epoch: 4/20...  Training Step: 707...  Training loss: 1.8007...  0.1479 sec/batch
Epoch: 4/20...  Training Step: 708...  Training loss: 1.7990...  0.1477 sec/batch
Epoch: 4/20...  Training Step: 709...  Training loss: 1.7808...  0.1484 sec/batch
Epoch: 4/20...  Training Step: 710...  Training loss: 1.7623...  0.1481 sec/batch
Epoch: 4/20...  Training Step: 711...  Training loss: 1.8037...  0.1489 sec/batch
Epoch: 4/20...  Training Step: 712...  Training loss: 1.7779...  0.1476 sec/batch
Epoch: 4/20...  Training Step: 713...  Training loss: 1.7950...  0.1481 sec/batch
Epoch: 4/20...  Training Step: 714...  Training loss: 1.7885...  0.1474 sec/batch
Epoch: 4/20...  

Epoch: 5/20...  Training Step: 803...  Training loss: 1.7209...  0.1507 sec/batch
Epoch: 5/20...  Training Step: 804...  Training loss: 1.7178...  0.1491 sec/batch
Epoch: 5/20...  Training Step: 805...  Training loss: 1.7380...  0.1469 sec/batch
Epoch: 5/20...  Training Step: 806...  Training loss: 1.7701...  0.1476 sec/batch
Epoch: 5/20...  Training Step: 807...  Training loss: 1.7275...  0.1473 sec/batch
Epoch: 5/20...  Training Step: 808...  Training loss: 1.7092...  0.1467 sec/batch
Epoch: 5/20...  Training Step: 809...  Training loss: 1.7426...  0.1468 sec/batch
Epoch: 5/20...  Training Step: 810...  Training loss: 1.7717...  0.1471 sec/batch
Epoch: 5/20...  Training Step: 811...  Training loss: 1.7374...  0.1502 sec/batch
Epoch: 5/20...  Training Step: 812...  Training loss: 1.7544...  0.1488 sec/batch
Epoch: 5/20...  Training Step: 813...  Training loss: 1.7188...  0.1501 sec/batch
Epoch: 5/20...  Training Step: 814...  Training loss: 1.7587...  0.1476 sec/batch
Epoch: 5/20...  

Epoch: 5/20...  Training Step: 903...  Training loss: 1.6703...  0.1474 sec/batch
Epoch: 5/20...  Training Step: 904...  Training loss: 1.6758...  0.1478 sec/batch
Epoch: 5/20...  Training Step: 905...  Training loss: 1.6654...  0.1486 sec/batch
Epoch: 5/20...  Training Step: 906...  Training loss: 1.6591...  0.1476 sec/batch
Epoch: 5/20...  Training Step: 907...  Training loss: 1.6574...  0.1480 sec/batch
Epoch: 5/20...  Training Step: 908...  Training loss: 1.6331...  0.1473 sec/batch
Epoch: 5/20...  Training Step: 909...  Training loss: 1.6867...  0.1505 sec/batch
Epoch: 5/20...  Training Step: 910...  Training loss: 1.6664...  0.1474 sec/batch
Epoch: 5/20...  Training Step: 911...  Training loss: 1.6735...  0.1481 sec/batch
Epoch: 5/20...  Training Step: 912...  Training loss: 1.6667...  0.1467 sec/batch
Epoch: 5/20...  Training Step: 913...  Training loss: 1.6842...  0.1481 sec/batch
Epoch: 5/20...  Training Step: 914...  Training loss: 1.6376...  0.1489 sec/batch
Epoch: 5/20...  

Epoch: 6/20...  Training Step: 1003...  Training loss: 1.6318...  0.1499 sec/batch
Epoch: 6/20...  Training Step: 1004...  Training loss: 1.6660...  0.1491 sec/batch
Epoch: 6/20...  Training Step: 1005...  Training loss: 1.6310...  0.1480 sec/batch
Epoch: 6/20...  Training Step: 1006...  Training loss: 1.6100...  0.1475 sec/batch
Epoch: 6/20...  Training Step: 1007...  Training loss: 1.6351...  0.1481 sec/batch
Epoch: 6/20...  Training Step: 1008...  Training loss: 1.6509...  0.1476 sec/batch
Epoch: 6/20...  Training Step: 1009...  Training loss: 1.6367...  0.1480 sec/batch
Epoch: 6/20...  Training Step: 1010...  Training loss: 1.6554...  0.1478 sec/batch
Epoch: 6/20...  Training Step: 1011...  Training loss: 1.6193...  0.1474 sec/batch
Epoch: 6/20...  Training Step: 1012...  Training loss: 1.6566...  0.1476 sec/batch
Epoch: 6/20...  Training Step: 1013...  Training loss: 1.6212...  0.1473 sec/batch
Epoch: 6/20...  Training Step: 1014...  Training loss: 1.6382...  0.1495 sec/batch
Epoc

Epoch: 6/20...  Training Step: 1103...  Training loss: 1.5897...  0.1479 sec/batch
Epoch: 6/20...  Training Step: 1104...  Training loss: 1.5808...  0.1491 sec/batch
Epoch: 6/20...  Training Step: 1105...  Training loss: 1.5662...  0.1485 sec/batch
Epoch: 6/20...  Training Step: 1106...  Training loss: 1.5490...  0.1483 sec/batch
Epoch: 6/20...  Training Step: 1107...  Training loss: 1.6017...  0.1477 sec/batch
Epoch: 6/20...  Training Step: 1108...  Training loss: 1.5915...  0.1470 sec/batch
Epoch: 6/20...  Training Step: 1109...  Training loss: 1.5868...  0.1478 sec/batch
Epoch: 6/20...  Training Step: 1110...  Training loss: 1.5805...  0.1482 sec/batch
Epoch: 6/20...  Training Step: 1111...  Training loss: 1.5930...  0.1482 sec/batch
Epoch: 6/20...  Training Step: 1112...  Training loss: 1.5479...  0.1483 sec/batch
Epoch: 6/20...  Training Step: 1113...  Training loss: 1.5420...  0.1478 sec/batch
Epoch: 6/20...  Training Step: 1114...  Training loss: 1.6097...  0.1488 sec/batch
Epoc

Epoch: 7/20...  Training Step: 1203...  Training loss: 1.5409...  0.1493 sec/batch
Epoch: 7/20...  Training Step: 1204...  Training loss: 1.5255...  0.1499 sec/batch
Epoch: 7/20...  Training Step: 1205...  Training loss: 1.5606...  0.1492 sec/batch
Epoch: 7/20...  Training Step: 1206...  Training loss: 1.5955...  0.1471 sec/batch
Epoch: 7/20...  Training Step: 1207...  Training loss: 1.5632...  0.1488 sec/batch
Epoch: 7/20...  Training Step: 1208...  Training loss: 1.5796...  0.1485 sec/batch
Epoch: 7/20...  Training Step: 1209...  Training loss: 1.5454...  0.1482 sec/batch
Epoch: 7/20...  Training Step: 1210...  Training loss: 1.5719...  0.1478 sec/batch
Epoch: 7/20...  Training Step: 1211...  Training loss: 1.5396...  0.1468 sec/batch
Epoch: 7/20...  Training Step: 1212...  Training loss: 1.5595...  0.1483 sec/batch
Epoch: 7/20...  Training Step: 1213...  Training loss: 1.5684...  0.1486 sec/batch
Epoch: 7/20...  Training Step: 1214...  Training loss: 1.5218...  0.1493 sec/batch
Epoc

Epoch: 7/20...  Training Step: 1303...  Training loss: 1.4940...  0.1469 sec/batch
Epoch: 7/20...  Training Step: 1304...  Training loss: 1.4803...  0.1481 sec/batch
Epoch: 7/20...  Training Step: 1305...  Training loss: 1.5175...  0.1482 sec/batch
Epoch: 7/20...  Training Step: 1306...  Training loss: 1.5203...  0.1486 sec/batch
Epoch: 7/20...  Training Step: 1307...  Training loss: 1.5077...  0.1482 sec/batch
Epoch: 7/20...  Training Step: 1308...  Training loss: 1.5063...  0.1481 sec/batch
Epoch: 7/20...  Training Step: 1309...  Training loss: 1.5177...  0.1484 sec/batch
Epoch: 7/20...  Training Step: 1310...  Training loss: 1.4801...  0.1471 sec/batch
Epoch: 7/20...  Training Step: 1311...  Training loss: 1.4667...  0.1467 sec/batch
Epoch: 7/20...  Training Step: 1312...  Training loss: 1.5250...  0.1483 sec/batch
Epoch: 7/20...  Training Step: 1313...  Training loss: 1.5106...  0.1470 sec/batch
Epoch: 7/20...  Training Step: 1314...  Training loss: 1.4663...  0.1512 sec/batch
Epoc

Epoch: 8/20...  Training Step: 1403...  Training loss: 1.4952...  0.1496 sec/batch
Epoch: 8/20...  Training Step: 1404...  Training loss: 1.5114...  0.1473 sec/batch
Epoch: 8/20...  Training Step: 1405...  Training loss: 1.4944...  0.1484 sec/batch
Epoch: 8/20...  Training Step: 1406...  Training loss: 1.5147...  0.1488 sec/batch
Epoch: 8/20...  Training Step: 1407...  Training loss: 1.4711...  0.1491 sec/batch
Epoch: 8/20...  Training Step: 1408...  Training loss: 1.5059...  0.1485 sec/batch
Epoch: 8/20...  Training Step: 1409...  Training loss: 1.4710...  0.1477 sec/batch
Epoch: 8/20...  Training Step: 1410...  Training loss: 1.4907...  0.1470 sec/batch
Epoch: 8/20...  Training Step: 1411...  Training loss: 1.4828...  0.1482 sec/batch
Epoch: 8/20...  Training Step: 1412...  Training loss: 1.4354...  0.1477 sec/batch
Epoch: 8/20...  Training Step: 1413...  Training loss: 1.4407...  0.1471 sec/batch
Epoch: 8/20...  Training Step: 1414...  Training loss: 1.5031...  0.1488 sec/batch
Epoc

Epoch: 8/20...  Training Step: 1503...  Training loss: 1.4567...  0.1475 sec/batch
Epoch: 8/20...  Training Step: 1504...  Training loss: 1.4613...  0.1476 sec/batch
Epoch: 8/20...  Training Step: 1505...  Training loss: 1.4481...  0.1477 sec/batch
Epoch: 8/20...  Training Step: 1506...  Training loss: 1.4450...  0.1479 sec/batch
Epoch: 8/20...  Training Step: 1507...  Training loss: 1.4602...  0.1480 sec/batch
Epoch: 8/20...  Training Step: 1508...  Training loss: 1.4248...  0.1480 sec/batch
Epoch: 8/20...  Training Step: 1509...  Training loss: 1.4100...  0.1471 sec/batch
Epoch: 8/20...  Training Step: 1510...  Training loss: 1.4655...  0.1472 sec/batch
Epoch: 8/20...  Training Step: 1511...  Training loss: 1.4543...  0.1474 sec/batch
Epoch: 8/20...  Training Step: 1512...  Training loss: 1.4094...  0.1480 sec/batch
Epoch: 8/20...  Training Step: 1513...  Training loss: 1.4771...  0.1473 sec/batch
Epoch: 8/20...  Training Step: 1514...  Training loss: 1.4655...  0.1490 sec/batch
Epoc

Epoch: 9/20...  Training Step: 1603...  Training loss: 1.4514...  0.1505 sec/batch
Epoch: 9/20...  Training Step: 1604...  Training loss: 1.4623...  0.1495 sec/batch
Epoch: 9/20...  Training Step: 1605...  Training loss: 1.4246...  0.1469 sec/batch
Epoch: 9/20...  Training Step: 1606...  Training loss: 1.4517...  0.1468 sec/batch
Epoch: 9/20...  Training Step: 1607...  Training loss: 1.4298...  0.1483 sec/batch
Epoch: 9/20...  Training Step: 1608...  Training loss: 1.4485...  0.1476 sec/batch
Epoch: 9/20...  Training Step: 1609...  Training loss: 1.4318...  0.1482 sec/batch
Epoch: 9/20...  Training Step: 1610...  Training loss: 1.3958...  0.1473 sec/batch
Epoch: 9/20...  Training Step: 1611...  Training loss: 1.4041...  0.1482 sec/batch
Epoch: 9/20...  Training Step: 1612...  Training loss: 1.4450...  0.1481 sec/batch
Epoch: 9/20...  Training Step: 1613...  Training loss: 1.4563...  0.1471 sec/batch
Epoch: 9/20...  Training Step: 1614...  Training loss: 1.4479...  0.1475 sec/batch
Epoc

Epoch: 9/20...  Training Step: 1703...  Training loss: 1.4031...  0.1511 sec/batch
Epoch: 9/20...  Training Step: 1704...  Training loss: 1.4012...  0.1474 sec/batch
Epoch: 9/20...  Training Step: 1705...  Training loss: 1.4125...  0.1482 sec/batch
Epoch: 9/20...  Training Step: 1706...  Training loss: 1.3777...  0.1488 sec/batch
Epoch: 9/20...  Training Step: 1707...  Training loss: 1.3695...  0.1481 sec/batch
Epoch: 9/20...  Training Step: 1708...  Training loss: 1.4179...  0.1472 sec/batch
Epoch: 9/20...  Training Step: 1709...  Training loss: 1.3994...  0.1475 sec/batch
Epoch: 9/20...  Training Step: 1710...  Training loss: 1.3607...  0.1474 sec/batch
Epoch: 9/20...  Training Step: 1711...  Training loss: 1.4256...  0.1474 sec/batch
Epoch: 9/20...  Training Step: 1712...  Training loss: 1.4134...  0.1480 sec/batch
Epoch: 9/20...  Training Step: 1713...  Training loss: 1.3955...  0.1493 sec/batch
Epoch: 9/20...  Training Step: 1714...  Training loss: 1.3746...  0.1485 sec/batch
Epoc

Epoch: 10/20...  Training Step: 1803...  Training loss: 1.3944...  0.1502 sec/batch
Epoch: 10/20...  Training Step: 1804...  Training loss: 1.4174...  0.1480 sec/batch
Epoch: 10/20...  Training Step: 1805...  Training loss: 1.3929...  0.1513 sec/batch
Epoch: 10/20...  Training Step: 1806...  Training loss: 1.4130...  0.1484 sec/batch
Epoch: 10/20...  Training Step: 1807...  Training loss: 1.4055...  0.1487 sec/batch
Epoch: 10/20...  Training Step: 1808...  Training loss: 1.3635...  0.1492 sec/batch
Epoch: 10/20...  Training Step: 1809...  Training loss: 1.3728...  0.1492 sec/batch
Epoch: 10/20...  Training Step: 1810...  Training loss: 1.4178...  0.1474 sec/batch
Epoch: 10/20...  Training Step: 1811...  Training loss: 1.4255...  0.1481 sec/batch
Epoch: 10/20...  Training Step: 1812...  Training loss: 1.4180...  0.1489 sec/batch
Epoch: 10/20...  Training Step: 1813...  Training loss: 1.3897...  0.1475 sec/batch
Epoch: 10/20...  Training Step: 1814...  Training loss: 1.3694...  0.1482 se

Epoch: 10/20...  Training Step: 1901...  Training loss: 1.3700...  0.1477 sec/batch
Epoch: 10/20...  Training Step: 1902...  Training loss: 1.3781...  0.1477 sec/batch
Epoch: 10/20...  Training Step: 1903...  Training loss: 1.3792...  0.1480 sec/batch
Epoch: 10/20...  Training Step: 1904...  Training loss: 1.3491...  0.1475 sec/batch
Epoch: 10/20...  Training Step: 1905...  Training loss: 1.3428...  0.1477 sec/batch
Epoch: 10/20...  Training Step: 1906...  Training loss: 1.3857...  0.1484 sec/batch
Epoch: 10/20...  Training Step: 1907...  Training loss: 1.3753...  0.1516 sec/batch
Epoch: 10/20...  Training Step: 1908...  Training loss: 1.3374...  0.1484 sec/batch
Epoch: 10/20...  Training Step: 1909...  Training loss: 1.3931...  0.1476 sec/batch
Epoch: 10/20...  Training Step: 1910...  Training loss: 1.3878...  0.1478 sec/batch
Epoch: 10/20...  Training Step: 1911...  Training loss: 1.3640...  0.1487 sec/batch
Epoch: 10/20...  Training Step: 1912...  Training loss: 1.3451...  0.1472 se

Epoch: 11/20...  Training Step: 1999...  Training loss: 1.3831...  0.1488 sec/batch
Epoch: 11/20...  Training Step: 2000...  Training loss: 1.3995...  0.1472 sec/batch
Epoch: 11/20...  Training Step: 2001...  Training loss: 1.3572...  0.1544 sec/batch
Epoch: 11/20...  Training Step: 2002...  Training loss: 1.3826...  0.1515 sec/batch
Epoch: 11/20...  Training Step: 2003...  Training loss: 1.3633...  0.1507 sec/batch
Epoch: 11/20...  Training Step: 2004...  Training loss: 1.3868...  0.1532 sec/batch
Epoch: 11/20...  Training Step: 2005...  Training loss: 1.3715...  0.1480 sec/batch
Epoch: 11/20...  Training Step: 2006...  Training loss: 1.3298...  0.1472 sec/batch
Epoch: 11/20...  Training Step: 2007...  Training loss: 1.3356...  0.1481 sec/batch
Epoch: 11/20...  Training Step: 2008...  Training loss: 1.3804...  0.1478 sec/batch
Epoch: 11/20...  Training Step: 2009...  Training loss: 1.3832...  0.1488 sec/batch
Epoch: 11/20...  Training Step: 2010...  Training loss: 1.3925...  0.1474 se

Epoch: 11/20...  Training Step: 2097...  Training loss: 1.3497...  0.1472 sec/batch
Epoch: 11/20...  Training Step: 2098...  Training loss: 1.3562...  0.1508 sec/batch
Epoch: 11/20...  Training Step: 2099...  Training loss: 1.3467...  0.1487 sec/batch
Epoch: 11/20...  Training Step: 2100...  Training loss: 1.3508...  0.1501 sec/batch
Epoch: 11/20...  Training Step: 2101...  Training loss: 1.3562...  0.1483 sec/batch
Epoch: 11/20...  Training Step: 2102...  Training loss: 1.3102...  0.1477 sec/batch
Epoch: 11/20...  Training Step: 2103...  Training loss: 1.3149...  0.1492 sec/batch
Epoch: 11/20...  Training Step: 2104...  Training loss: 1.3524...  0.1491 sec/batch
Epoch: 11/20...  Training Step: 2105...  Training loss: 1.3405...  0.1477 sec/batch
Epoch: 11/20...  Training Step: 2106...  Training loss: 1.2997...  0.1477 sec/batch
Epoch: 11/20...  Training Step: 2107...  Training loss: 1.3660...  0.1485 sec/batch
Epoch: 11/20...  Training Step: 2108...  Training loss: 1.3551...  0.1489 se

Epoch: 12/20...  Training Step: 2195...  Training loss: 1.3605...  0.1473 sec/batch
Epoch: 12/20...  Training Step: 2196...  Training loss: 1.3758...  0.1480 sec/batch
Epoch: 12/20...  Training Step: 2197...  Training loss: 1.3522...  0.1466 sec/batch
Epoch: 12/20...  Training Step: 2198...  Training loss: 1.3659...  0.1481 sec/batch
Epoch: 12/20...  Training Step: 2199...  Training loss: 1.3411...  0.1487 sec/batch
Epoch: 12/20...  Training Step: 2200...  Training loss: 1.3617...  0.1480 sec/batch
Epoch: 12/20...  Training Step: 2201...  Training loss: 1.3426...  0.1519 sec/batch
Epoch: 12/20...  Training Step: 2202...  Training loss: 1.3594...  0.1531 sec/batch
Epoch: 12/20...  Training Step: 2203...  Training loss: 1.3515...  0.1502 sec/batch
Epoch: 12/20...  Training Step: 2204...  Training loss: 1.3065...  0.1501 sec/batch
Epoch: 12/20...  Training Step: 2205...  Training loss: 1.3095...  0.1492 sec/batch
Epoch: 12/20...  Training Step: 2206...  Training loss: 1.3698...  0.1501 se

Epoch: 12/20...  Training Step: 2293...  Training loss: 1.3000...  0.1467 sec/batch
Epoch: 12/20...  Training Step: 2294...  Training loss: 1.2860...  0.1497 sec/batch
Epoch: 12/20...  Training Step: 2295...  Training loss: 1.3298...  0.1482 sec/batch
Epoch: 12/20...  Training Step: 2296...  Training loss: 1.3370...  0.1507 sec/batch
Epoch: 12/20...  Training Step: 2297...  Training loss: 1.3246...  0.1501 sec/batch
Epoch: 12/20...  Training Step: 2298...  Training loss: 1.3330...  0.1486 sec/batch
Epoch: 12/20...  Training Step: 2299...  Training loss: 1.3312...  0.1492 sec/batch
Epoch: 12/20...  Training Step: 2300...  Training loss: 1.2986...  0.1493 sec/batch
Epoch: 12/20...  Training Step: 2301...  Training loss: 1.2864...  0.1478 sec/batch
Epoch: 12/20...  Training Step: 2302...  Training loss: 1.3340...  0.1476 sec/batch
Epoch: 12/20...  Training Step: 2303...  Training loss: 1.3253...  0.1492 sec/batch
Epoch: 12/20...  Training Step: 2304...  Training loss: 1.2847...  0.1495 se

Epoch: 13/20...  Training Step: 2391...  Training loss: 1.3154...  0.1479 sec/batch
Epoch: 13/20...  Training Step: 2392...  Training loss: 1.3019...  0.1471 sec/batch
Epoch: 13/20...  Training Step: 2393...  Training loss: 1.3365...  0.1486 sec/batch
Epoch: 13/20...  Training Step: 2394...  Training loss: 1.3491...  0.1488 sec/batch
Epoch: 13/20...  Training Step: 2395...  Training loss: 1.3321...  0.1486 sec/batch
Epoch: 13/20...  Training Step: 2396...  Training loss: 1.3515...  0.1486 sec/batch
Epoch: 13/20...  Training Step: 2397...  Training loss: 1.3160...  0.1469 sec/batch
Epoch: 13/20...  Training Step: 2398...  Training loss: 1.3321...  0.1474 sec/batch
Epoch: 13/20...  Training Step: 2399...  Training loss: 1.3159...  0.1473 sec/batch
Epoch: 13/20...  Training Step: 2400...  Training loss: 1.3318...  0.1475 sec/batch
Epoch: 13/20...  Training Step: 2401...  Training loss: 1.3235...  0.1556 sec/batch
Epoch: 13/20...  Training Step: 2402...  Training loss: 1.2828...  0.1534 se

Epoch: 13/20...  Training Step: 2489...  Training loss: 1.3221...  0.1476 sec/batch
Epoch: 13/20...  Training Step: 2490...  Training loss: 1.3075...  0.1510 sec/batch
Epoch: 13/20...  Training Step: 2491...  Training loss: 1.2870...  0.1483 sec/batch
Epoch: 13/20...  Training Step: 2492...  Training loss: 1.2638...  0.1483 sec/batch
Epoch: 13/20...  Training Step: 2493...  Training loss: 1.3111...  0.1476 sec/batch
Epoch: 13/20...  Training Step: 2494...  Training loss: 1.3298...  0.1477 sec/batch
Epoch: 13/20...  Training Step: 2495...  Training loss: 1.3051...  0.1473 sec/batch
Epoch: 13/20...  Training Step: 2496...  Training loss: 1.3205...  0.1471 sec/batch
Epoch: 13/20...  Training Step: 2497...  Training loss: 1.3107...  0.1474 sec/batch
Epoch: 13/20...  Training Step: 2498...  Training loss: 1.2791...  0.1482 sec/batch
Epoch: 13/20...  Training Step: 2499...  Training loss: 1.2622...  0.1485 sec/batch
Epoch: 13/20...  Training Step: 2500...  Training loss: 1.3103...  0.1486 se

Epoch: 14/20...  Training Step: 2587...  Training loss: 1.3108...  0.1483 sec/batch
Epoch: 14/20...  Training Step: 2588...  Training loss: 1.3204...  0.1492 sec/batch
Epoch: 14/20...  Training Step: 2589...  Training loss: 1.2850...  0.1479 sec/batch
Epoch: 14/20...  Training Step: 2590...  Training loss: 1.2799...  0.1467 sec/batch
Epoch: 14/20...  Training Step: 2591...  Training loss: 1.3130...  0.1474 sec/batch
Epoch: 14/20...  Training Step: 2592...  Training loss: 1.3244...  0.1491 sec/batch
Epoch: 14/20...  Training Step: 2593...  Training loss: 1.3083...  0.1484 sec/batch
Epoch: 14/20...  Training Step: 2594...  Training loss: 1.3344...  0.1474 sec/batch
Epoch: 14/20...  Training Step: 2595...  Training loss: 1.3001...  0.1483 sec/batch
Epoch: 14/20...  Training Step: 2596...  Training loss: 1.3115...  0.1485 sec/batch
Epoch: 14/20...  Training Step: 2597...  Training loss: 1.2944...  0.1479 sec/batch
Epoch: 14/20...  Training Step: 2598...  Training loss: 1.3284...  0.1474 se

Epoch: 14/20...  Training Step: 2685...  Training loss: 1.2830...  0.1493 sec/batch
Epoch: 14/20...  Training Step: 2686...  Training loss: 1.2971...  0.1476 sec/batch
Epoch: 14/20...  Training Step: 2687...  Training loss: 1.3018...  0.1483 sec/batch
Epoch: 14/20...  Training Step: 2688...  Training loss: 1.2809...  0.1510 sec/batch
Epoch: 14/20...  Training Step: 2689...  Training loss: 1.2612...  0.1487 sec/batch
Epoch: 14/20...  Training Step: 2690...  Training loss: 1.2511...  0.1479 sec/batch
Epoch: 14/20...  Training Step: 2691...  Training loss: 1.2972...  0.1474 sec/batch
Epoch: 14/20...  Training Step: 2692...  Training loss: 1.3025...  0.1482 sec/batch
Epoch: 14/20...  Training Step: 2693...  Training loss: 1.2962...  0.1476 sec/batch
Epoch: 14/20...  Training Step: 2694...  Training loss: 1.2894...  0.1480 sec/batch
Epoch: 14/20...  Training Step: 2695...  Training loss: 1.2868...  0.1496 sec/batch
Epoch: 14/20...  Training Step: 2696...  Training loss: 1.2711...  0.1487 se

Epoch: 15/20...  Training Step: 2783...  Training loss: 1.2741...  0.1477 sec/batch
Epoch: 15/20...  Training Step: 2784...  Training loss: 1.2889...  0.1477 sec/batch
Epoch: 15/20...  Training Step: 2785...  Training loss: 1.2950...  0.1485 sec/batch
Epoch: 15/20...  Training Step: 2786...  Training loss: 1.2912...  0.1502 sec/batch
Epoch: 15/20...  Training Step: 2787...  Training loss: 1.2777...  0.1482 sec/batch
Epoch: 15/20...  Training Step: 2788...  Training loss: 1.2636...  0.1470 sec/batch
Epoch: 15/20...  Training Step: 2789...  Training loss: 1.3132...  0.1471 sec/batch
Epoch: 15/20...  Training Step: 2790...  Training loss: 1.3060...  0.1490 sec/batch
Epoch: 15/20...  Training Step: 2791...  Training loss: 1.2898...  0.1477 sec/batch
Epoch: 15/20...  Training Step: 2792...  Training loss: 1.3115...  0.1475 sec/batch
Epoch: 15/20...  Training Step: 2793...  Training loss: 1.2850...  0.1487 sec/batch
Epoch: 15/20...  Training Step: 2794...  Training loss: 1.3076...  0.1489 se

Epoch: 15/20...  Training Step: 2881...  Training loss: 1.2646...  0.1471 sec/batch
Epoch: 15/20...  Training Step: 2882...  Training loss: 1.2896...  0.1478 sec/batch
Epoch: 15/20...  Training Step: 2883...  Training loss: 1.2661...  0.1485 sec/batch
Epoch: 15/20...  Training Step: 2884...  Training loss: 1.2914...  0.1478 sec/batch
Epoch: 15/20...  Training Step: 2885...  Training loss: 1.2880...  0.1475 sec/batch
Epoch: 15/20...  Training Step: 2886...  Training loss: 1.2697...  0.1466 sec/batch
Epoch: 15/20...  Training Step: 2887...  Training loss: 1.2506...  0.1483 sec/batch
Epoch: 15/20...  Training Step: 2888...  Training loss: 1.2400...  0.1492 sec/batch
Epoch: 15/20...  Training Step: 2889...  Training loss: 1.2702...  0.1472 sec/batch
Epoch: 15/20...  Training Step: 2890...  Training loss: 1.2921...  0.1486 sec/batch
Epoch: 15/20...  Training Step: 2891...  Training loss: 1.2744...  0.1475 sec/batch
Epoch: 15/20...  Training Step: 2892...  Training loss: 1.2811...  0.1482 se

Epoch: 16/20...  Training Step: 2979...  Training loss: 1.2837...  0.1488 sec/batch
Epoch: 16/20...  Training Step: 2980...  Training loss: 1.2713...  0.1527 sec/batch
Epoch: 16/20...  Training Step: 2981...  Training loss: 1.2646...  0.1495 sec/batch
Epoch: 16/20...  Training Step: 2982...  Training loss: 1.2676...  0.1493 sec/batch
Epoch: 16/20...  Training Step: 2983...  Training loss: 1.2773...  0.1488 sec/batch
Epoch: 16/20...  Training Step: 2984...  Training loss: 1.2810...  0.1488 sec/batch
Epoch: 16/20...  Training Step: 2985...  Training loss: 1.2569...  0.1476 sec/batch
Epoch: 16/20...  Training Step: 2986...  Training loss: 1.2544...  0.1464 sec/batch
Epoch: 16/20...  Training Step: 2987...  Training loss: 1.2871...  0.1483 sec/batch
Epoch: 16/20...  Training Step: 2988...  Training loss: 1.2888...  0.1471 sec/batch
Epoch: 16/20...  Training Step: 2989...  Training loss: 1.2761...  0.1491 sec/batch
Epoch: 16/20...  Training Step: 2990...  Training loss: 1.2928...  0.1489 se

Epoch: 16/20...  Training Step: 3077...  Training loss: 1.2671...  0.1484 sec/batch
Epoch: 16/20...  Training Step: 3078...  Training loss: 1.2724...  0.1483 sec/batch
Epoch: 16/20...  Training Step: 3079...  Training loss: 1.2559...  0.1477 sec/batch
Epoch: 16/20...  Training Step: 3080...  Training loss: 1.2791...  0.1496 sec/batch
Epoch: 16/20...  Training Step: 3081...  Training loss: 1.2506...  0.1479 sec/batch
Epoch: 16/20...  Training Step: 3082...  Training loss: 1.2799...  0.1478 sec/batch
Epoch: 16/20...  Training Step: 3083...  Training loss: 1.2730...  0.1494 sec/batch
Epoch: 16/20...  Training Step: 3084...  Training loss: 1.2610...  0.1478 sec/batch
Epoch: 16/20...  Training Step: 3085...  Training loss: 1.2424...  0.1488 sec/batch
Epoch: 16/20...  Training Step: 3086...  Training loss: 1.2255...  0.1481 sec/batch
Epoch: 16/20...  Training Step: 3087...  Training loss: 1.2682...  0.1509 sec/batch
Epoch: 16/20...  Training Step: 3088...  Training loss: 1.2820...  0.1490 se

Epoch: 17/20...  Training Step: 3175...  Training loss: 1.2730...  0.1476 sec/batch
Epoch: 17/20...  Training Step: 3176...  Training loss: 1.2584...  0.1496 sec/batch
Epoch: 17/20...  Training Step: 3177...  Training loss: 1.2777...  0.1479 sec/batch
Epoch: 17/20...  Training Step: 3178...  Training loss: 1.2723...  0.1504 sec/batch
Epoch: 17/20...  Training Step: 3179...  Training loss: 1.2478...  0.1481 sec/batch
Epoch: 17/20...  Training Step: 3180...  Training loss: 1.2613...  0.1478 sec/batch
Epoch: 17/20...  Training Step: 3181...  Training loss: 1.2692...  0.1482 sec/batch
Epoch: 17/20...  Training Step: 3182...  Training loss: 1.2838...  0.1484 sec/batch
Epoch: 17/20...  Training Step: 3183...  Training loss: 1.2395...  0.1488 sec/batch
Epoch: 17/20...  Training Step: 3184...  Training loss: 1.2392...  0.1489 sec/batch
Epoch: 17/20...  Training Step: 3185...  Training loss: 1.2700...  0.1508 sec/batch
Epoch: 17/20...  Training Step: 3186...  Training loss: 1.2845...  0.1484 se

Epoch: 17/20...  Training Step: 3273...  Training loss: 1.2404...  0.1480 sec/batch
Epoch: 17/20...  Training Step: 3274...  Training loss: 1.2471...  0.1486 sec/batch
Epoch: 17/20...  Training Step: 3275...  Training loss: 1.2534...  0.1475 sec/batch
Epoch: 17/20...  Training Step: 3276...  Training loss: 1.2622...  0.1482 sec/batch
Epoch: 17/20...  Training Step: 3277...  Training loss: 1.2507...  0.1480 sec/batch
Epoch: 17/20...  Training Step: 3278...  Training loss: 1.2618...  0.1479 sec/batch
Epoch: 17/20...  Training Step: 3279...  Training loss: 1.2445...  0.1472 sec/batch
Epoch: 17/20...  Training Step: 3280...  Training loss: 1.2590...  0.1486 sec/batch
Epoch: 17/20...  Training Step: 3281...  Training loss: 1.2557...  0.1493 sec/batch
Epoch: 17/20...  Training Step: 3282...  Training loss: 1.2503...  0.1492 sec/batch
Epoch: 17/20...  Training Step: 3283...  Training loss: 1.2273...  0.1482 sec/batch
Epoch: 17/20...  Training Step: 3284...  Training loss: 1.2144...  0.1477 se

Epoch: 18/20...  Training Step: 3371...  Training loss: 1.2325...  0.1478 sec/batch
Epoch: 18/20...  Training Step: 3372...  Training loss: 1.2207...  0.1480 sec/batch
Epoch: 18/20...  Training Step: 3373...  Training loss: 1.2490...  0.1482 sec/batch
Epoch: 18/20...  Training Step: 3374...  Training loss: 1.2487...  0.1470 sec/batch
Epoch: 18/20...  Training Step: 3375...  Training loss: 1.2643...  0.1476 sec/batch
Epoch: 18/20...  Training Step: 3376...  Training loss: 1.2587...  0.1484 sec/batch
Epoch: 18/20...  Training Step: 3377...  Training loss: 1.2436...  0.1510 sec/batch
Epoch: 18/20...  Training Step: 3378...  Training loss: 1.2519...  0.1478 sec/batch
Epoch: 18/20...  Training Step: 3379...  Training loss: 1.2559...  0.1484 sec/batch
Epoch: 18/20...  Training Step: 3380...  Training loss: 1.2648...  0.1479 sec/batch
Epoch: 18/20...  Training Step: 3381...  Training loss: 1.2332...  0.1474 sec/batch
Epoch: 18/20...  Training Step: 3382...  Training loss: 1.2333...  0.1489 se

Epoch: 18/20...  Training Step: 3469...  Training loss: 1.2463...  0.1476 sec/batch
Epoch: 18/20...  Training Step: 3470...  Training loss: 1.2374...  0.1470 sec/batch
Epoch: 18/20...  Training Step: 3471...  Training loss: 1.2280...  0.1473 sec/batch
Epoch: 18/20...  Training Step: 3472...  Training loss: 1.2351...  0.1477 sec/batch
Epoch: 18/20...  Training Step: 3473...  Training loss: 1.2462...  0.1507 sec/batch
Epoch: 18/20...  Training Step: 3474...  Training loss: 1.2373...  0.1484 sec/batch
Epoch: 18/20...  Training Step: 3475...  Training loss: 1.2382...  0.1476 sec/batch
Epoch: 18/20...  Training Step: 3476...  Training loss: 1.2594...  0.1481 sec/batch
Epoch: 18/20...  Training Step: 3477...  Training loss: 1.2281...  0.1483 sec/batch
Epoch: 18/20...  Training Step: 3478...  Training loss: 1.2492...  0.1475 sec/batch
Epoch: 18/20...  Training Step: 3479...  Training loss: 1.2588...  0.1471 sec/batch
Epoch: 18/20...  Training Step: 3480...  Training loss: 1.2280...  0.1488 se

Epoch: 19/20...  Training Step: 3567...  Training loss: 1.2384...  0.1494 sec/batch
Epoch: 19/20...  Training Step: 3568...  Training loss: 1.2587...  0.1476 sec/batch
Epoch: 19/20...  Training Step: 3569...  Training loss: 1.2143...  0.1473 sec/batch
Epoch: 19/20...  Training Step: 3570...  Training loss: 1.2050...  0.1477 sec/batch
Epoch: 19/20...  Training Step: 3571...  Training loss: 1.2385...  0.1473 sec/batch
Epoch: 19/20...  Training Step: 3572...  Training loss: 1.2453...  0.1517 sec/batch
Epoch: 19/20...  Training Step: 3573...  Training loss: 1.2494...  0.1493 sec/batch
Epoch: 19/20...  Training Step: 3574...  Training loss: 1.2538...  0.1478 sec/batch
Epoch: 19/20...  Training Step: 3575...  Training loss: 1.2208...  0.1471 sec/batch
Epoch: 19/20...  Training Step: 3576...  Training loss: 1.2331...  0.1486 sec/batch
Epoch: 19/20...  Training Step: 3577...  Training loss: 1.2458...  0.1476 sec/batch
Epoch: 19/20...  Training Step: 3578...  Training loss: 1.2431...  0.1475 se

Epoch: 19/20...  Training Step: 3665...  Training loss: 1.2354...  0.1471 sec/batch
Epoch: 19/20...  Training Step: 3666...  Training loss: 1.2226...  0.1480 sec/batch
Epoch: 19/20...  Training Step: 3667...  Training loss: 1.2340...  0.1484 sec/batch
Epoch: 19/20...  Training Step: 3668...  Training loss: 1.2251...  0.1476 sec/batch
Epoch: 19/20...  Training Step: 3669...  Training loss: 1.2215...  0.1466 sec/batch
Epoch: 19/20...  Training Step: 3670...  Training loss: 1.2192...  0.1483 sec/batch
Epoch: 19/20...  Training Step: 3671...  Training loss: 1.2418...  0.1494 sec/batch
Epoch: 19/20...  Training Step: 3672...  Training loss: 1.2358...  0.1472 sec/batch
Epoch: 19/20...  Training Step: 3673...  Training loss: 1.2199...  0.1484 sec/batch
Epoch: 19/20...  Training Step: 3674...  Training loss: 1.2588...  0.1468 sec/batch
Epoch: 19/20...  Training Step: 3675...  Training loss: 1.2083...  0.1483 sec/batch
Epoch: 19/20...  Training Step: 3676...  Training loss: 1.2264...  0.1469 se

Epoch: 20/20...  Training Step: 3763...  Training loss: 1.3555...  0.1490 sec/batch
Epoch: 20/20...  Training Step: 3764...  Training loss: 1.2519...  0.1486 sec/batch
Epoch: 20/20...  Training Step: 3765...  Training loss: 1.2305...  0.1477 sec/batch
Epoch: 20/20...  Training Step: 3766...  Training loss: 1.2518...  0.1487 sec/batch
Epoch: 20/20...  Training Step: 3767...  Training loss: 1.2007...  0.1499 sec/batch
Epoch: 20/20...  Training Step: 3768...  Training loss: 1.2055...  0.1476 sec/batch
Epoch: 20/20...  Training Step: 3769...  Training loss: 1.2339...  0.1484 sec/batch
Epoch: 20/20...  Training Step: 3770...  Training loss: 1.2224...  0.1474 sec/batch
Epoch: 20/20...  Training Step: 3771...  Training loss: 1.2373...  0.1479 sec/batch
Epoch: 20/20...  Training Step: 3772...  Training loss: 1.2310...  0.1477 sec/batch
Epoch: 20/20...  Training Step: 3773...  Training loss: 1.2217...  0.1489 sec/batch
Epoch: 20/20...  Training Step: 3774...  Training loss: 1.2381...  0.1510 se

Epoch: 20/20...  Training Step: 3861...  Training loss: 1.2007...  0.1482 sec/batch
Epoch: 20/20...  Training Step: 3862...  Training loss: 1.1959...  0.1480 sec/batch
Epoch: 20/20...  Training Step: 3863...  Training loss: 1.2267...  0.1493 sec/batch
Epoch: 20/20...  Training Step: 3864...  Training loss: 1.2114...  0.1480 sec/batch
Epoch: 20/20...  Training Step: 3865...  Training loss: 1.2234...  0.1468 sec/batch
Epoch: 20/20...  Training Step: 3866...  Training loss: 1.2173...  0.1485 sec/batch
Epoch: 20/20...  Training Step: 3867...  Training loss: 1.2187...  0.1487 sec/batch
Epoch: 20/20...  Training Step: 3868...  Training loss: 1.2237...  0.1488 sec/batch
Epoch: 20/20...  Training Step: 3869...  Training loss: 1.2189...  0.1477 sec/batch
Epoch: 20/20...  Training Step: 3870...  Training loss: 1.2217...  0.1475 sec/batch
Epoch: 20/20...  Training Step: 3871...  Training loss: 1.2078...  0.1482 sec/batch
Epoch: 20/20...  Training Step: 3872...  Training loss: 1.2391...  0.1479 se

Epoch: 20/20...  Training Step: 3959...  Training loss: 1.2127...  0.1472 sec/batch
Epoch: 20/20...  Training Step: 3960...  Training loss: 1.2155...  0.1483 sec/batch


#### Saved checkpoints

Read up on saving and loading checkpoints here: https://www.tensorflow.org/programmers_guide/variables

In [22]:
tf.train.get_checkpoint_state('checkpoints')

model_checkpoint_path: "checkpoints/i3960_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i200_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i400_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i600_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i800_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i1000_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i1200_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i1400_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i1600_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i1800_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i2000_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i2200_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i2400_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i2600_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i2800_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i3000_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i3200_l512.ckpt"
all_model_checkpoint_pa

## Sampling

Now that the network is trained, we'll can use it to generate new text. The idea is that we pass in a character, then the network will predict the next character. We can use the new one, to predict the next one. And we keep doing this to generate all new text. I also included some functionality to prime the network with some text by passing in a string and building up a state from that.

The network gives us predictions for each character. To reduce noise and make things a little less random, I'm going to only choose a new character from the top N most likely characters.



In [23]:
def pick_top_n(preds, vocab_size, top_n=5):
    p = np.squeeze(preds)
    p[np.argsort(p)[:-top_n]] = 0
    p = p / np.sum(p)
    c = np.random.choice(vocab_size, 1, p=p)[0]
    return c

In [24]:
def sample(checkpoint, n_samples, lstm_size, vocab_size, prime="The "):
    samples = [c for c in prime]
    model = CharRNN(len(vocab), lstm_size=lstm_size, sampling=True)
    saver = tf.train.Saver()
    with tf.Session() as sess:
        saver.restore(sess, checkpoint)
        new_state = sess.run(model.initial_state)
        for c in prime:
            x = np.zeros((1, 1))
            x[0,0] = vocab_to_int[c]
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

        c = pick_top_n(preds, len(vocab))
        samples.append(int_to_vocab[c])

        for i in range(n_samples):
            x[0,0] = c
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

            c = pick_top_n(preds, len(vocab))
            samples.append(int_to_vocab[c])
        
    return ''.join(samples)

Here, pass in the path to a checkpoint and sample from the network.

In [25]:
tf.train.latest_checkpoint('checkpoints')

'checkpoints/i3960_l512.ckpt'

In [26]:
checkpoint = tf.train.latest_checkpoint('checkpoints')
samp = sample(checkpoint, 2000, lstm_size, len(vocab), prime="Far")
print(samp)

Farens. The man and this presence there was a long whell against the
serfice. And she would have seen a dest of sorry of any arrangements,
true. But the side house was in the money about the chief same, and
that he had to say to all his face, with some significance for his wife
that he had come and done to the penslition of a little and sounds of
the society, and always was in her and horses, and that that they
could not be a chalacteristic on her so second become in her soul that it
was all sincerity, and her clothest having been talking to horror of
a presine that was something was all his mother had no station.

The conversation had suddenly had not been anything.

Sometying her health she came over the services, had sat down again, and
at the conversation was not in the strange shreed to the door, and with
his sight of the party, the sick man thinking the secret of the mother
when they had brought a humored friends, and the prayers that he could not
let him any more and marking thi

In [27]:
checkpoint = 'checkpoints/i200_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

Fard,. ""
I"
"The tat he winse he wos al alt ong the hor an thot hed the
the sin the sand we he sos and se th the an soris he as oth thes sosed to he the he ad ond on har soron sha sas sitis he
sentes the he wis as arton thir ans on ond wome to whe the sos thes sosit to the sos at hos ho she sis the she him an tot thes th an setit and wo he angeras,. Tho hor ho wot thime
ne tot ha to we we he won thar al thir send tougtint ting and wh wamed, the the her what hot wit he wat ta hor,
thing th whe tousederede sad sithe the the he se the han shes oress ho tot on here an on ot to he the hhressasesid thise where ans andentor tat the
t the won he ans te hite wost hin sos torinnd
tare wes to se her
inntor ond tot ont ate
silt wens
thithe serede ho he the soros, sers on asis and af on he tare sin hos tot this won oth the he tins, and ang tee ar the ant oud thot woth shat ha lan and sithe to she sos thoth sar te sesilt ther singetin to he te artor to ho he
wans he ans her han ase and. 
I hind was

In [28]:
checkpoint = 'checkpoints/i600_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

Farnt out a seenen a doons the werly a prostines, bet of to as sone him, al her his and and she had booke word and wert on her had and said to hoult, sto stat to she whon he wond to
denting andond to stat had he he seed a sele to the corsions.

"The more when she shead, thourg that so he had and to the sort, sunding him his and and sace and where her
headed he said
the haress and than sheard her, her has thing his stalith his tongenter," she said
he dasted the monting the sond of
their that allong her ald
have a tare him that to the somesily wourd to dive in and som her and whene the sead, and withon te said whine and had sail he having had
same to sime her has
antanter that
she she distlidion of her heally.

"When, an the pinter on atone with
the pasting, and sooked hus a sant of her his her ander was having to the panting to shingher at a shiss to thow to and walk nover as to the portanion," said Stepan'Akknavitcch with which all she coundsess in this his,
boring the panitiou, and
at

In [29]:
checkpoint = 'checkpoints/i1200_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

Farcial the
confiring to the mone of the correm and thinds. She
she saw the
streads of herself hand only astended of the carres to her his some of the princess of which he came him of
all that his white the dreasing of
thisking the princess and with she was she had
bettee a still and he was happined, with the pood on the mush to the peaters and seet it.

"The possess a streatich, the may were notine at his mate a misted
and the
man of the mother at the same of the seem her
felt. He had not here.

"I conest only be alw you thinking that the partion
of their said."

"A much then you make all her
somether. Hower their centing
about
this, and I won't give it in
himself.
I had not come at any see it will that there she chile no one that him.

"The distiction with you all.... It was
a mone of the mind were starding to the simple to a mone. It to be to ser in the place," said Vronsky.
"And a plais in
his face, has alled in the consess on at they to gan in the sint
at as that
he would not be a